// Generated by wxt
export {}
declare global {
  const CSPAnalyzer: typeof import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/csp-analyzer').CSPAnalyzer
  const CSPReporter: typeof import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/csp-reporter').CSPReporter
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const detectLoginPage: typeof import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/login-detector').detectLoginPage
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const findPrivacyPolicy: typeof import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/privacy-finder').findPrivacyPolicy
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isLoginPage: typeof import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/login-detector').isLoginPage
  const onCookieChange: typeof import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/cookie-monitor').onCookieChange
  const startCookieMonitor: typeof import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/cookie-monitor').startCookieMonitor
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { CookieChangeCallback } from '/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/cookie-monitor'
  import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/cookie-monitor')
  // @ts-ignore
  export type { CSPAnalyzer } from '/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/csp-analyzer'
  import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/csp-analyzer')
  // @ts-ignore
  export type { CSPReporter, ReportPayload } from '/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/csp-reporter'
  import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/csp-reporter')
  // @ts-ignore
  export type { LoginDetectionResult } from '/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/login-detector'
  import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/login-detector')
  // @ts-ignore
  export type { PrivacyPolicyResult } from '/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/privacy-finder'
  import('/Users/hikae/ghq/github.com/HikaruEgashira/service-detection-integrate-csp-auditor/app/extension/utils/privacy-finder')
}
