import type { CSSProperties } from "preact/compat";

export const dashboardStyles: Record<string, CSSProperties> = {
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "24px",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    color: "hsl(0 0% 10%)",
    lineHeight: 1.5,
  },
  header: {
    marginBottom: "24px",
  },
  title: {
    fontSize: "24px",
    fontWeight: 600,
    margin: 0,
    marginBottom: "8px",
  },
  subtitle: {
    color: "hsl(0 0% 50%)",
    fontSize: "14px",
  },
  loading: {
    textAlign: "center",
    padding: "48px",
    color: "hsl(0 0% 60%)",
  },
  statsGrid: {
    display: "flex",
    gap: "24px",
    flexWrap: "wrap",
    marginBottom: "24px",
  },
  statCard: {
    background: "white",
    padding: "16px 24px",
    borderRadius: "4px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  statValue: {
    fontSize: "32px",
    fontWeight: 700,
    color: "hsl(0 0% 20%)",
  },
  statLabel: {
    fontSize: "12px",
    color: "hsl(0 0% 50%)",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "24px",
  },
  btn: {
    padding: "8px 16px",
    background: "hsl(0 0% 20%)",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
  },
  btnSecondary: {
    padding: "8px 16px",
    background: "hsl(0 0% 90%)",
    color: "hsl(0 0% 30%)",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "13px",
  },
  refreshNote: {
    fontSize: "12px",
    color: "hsl(0 0% 60%)",
    marginLeft: "auto",
  },
  section: {
    marginBottom: "24px",
  },
  sectionTitle: {
    fontSize: "18px",
    marginBottom: "12px",
    color: "hsl(0 0% 30%)",
  },
  card: {
    background: "white",
    padding: "16px",
    borderRadius: "4px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  cardTitle: {
    fontSize: "14px",
    marginBottom: "12px",
    color: "hsl(0 0% 40%)",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  statsColumns: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13px",
  },
  th: {
    background: "hsl(0 0% 97%)",
    borderBottom: "1px solid hsl(0 0% 85%)",
    fontWeight: 600,
    fontSize: "11px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    color: "hsl(0 0% 50%)",
    padding: "8px 12px",
    textAlign: "left",
  },
  td: {
    padding: "8px 12px",
    borderBottom: "1px solid hsl(0 0% 95%)",
  },
  tdUrl: {
    padding: "8px 12px",
    borderBottom: "1px solid hsl(0 0% 95%)",
    wordBreak: "break-all",
    maxWidth: "300px",
  },
  tr: {},
  code: {
    fontFamily: "'Menlo', monospace",
    fontSize: "11px",
    background: "hsl(0 0% 95%)",
    padding: "2px 4px",
    borderRadius: "2px",
  },
  badge: {
    display: "inline-block",
    padding: "2px 6px",
    background: "hsl(0 0% 90%)",
    borderRadius: "2px",
    fontSize: "11px",
  },
  empty: {
    color: "hsl(0 0% 60%)",
    padding: "24px",
    textAlign: "center",
  },
  more: {
    padding: "8px",
    color: "hsl(0 0% 60%)",
    fontSize: "12px",
  },
};
